### ISSUE TITLE
添加水印，报org.ofdrw.pkg.container.DocDir cannot be cast to org.ofdrw.pkg.container.PageDir

### ISSUE THREAD

**Issue by cheneymq** [ofdrw/ofdrw#120]
用的就是测试类WatermarkTest-->addWatermark方法，只是发票用的自己找的一张ofd
[ofd.zip](https://github.com/ofdrw/ofdrw/files/6498857/ofd.zip)

**Comment by Trisia** [comment]
该问题将于 1.9.3 版本修复
