### ISSUE TITLE
印章展示问题

### ISSUE THREAD

**Issue by zero20121222** [ofdrw/ofdrw#123]
在OFD的发票上，国家税务总局的印章是在文字之下的，这个在处理上应该要调整下
![image](https://user-images.githubusercontent.com/6296864/120422070-1afb7880-c39a-11eb-8828-3bb7c35fb196.png)

**Comment by Trisia** [comment]
印章与原文的上下关系，在印章签章时候并没有相关参数来指定，因此没有足够的信息来判断印章应该是在文字上方或下方。
