### ISSUE TITLE
使用水印例子添加水印后，调佣close后ofddir工作目录不能删除

### ISSUE THREAD

**Issue by jackle96033** [ofdrw/ofdrw#142]
使用版本1.17.6, 调用水印例子添加水印，最后调用ofdDoc.close()后，ofddir工作目录不能删除，版本1.9.0无此问题

**Comment by Trisia** [comment]
我未能重现该问题

**Comment by Trisia** [comment]
1.17.16 现在改用 forceDelete 该问题有所改善。
