### ISSUE TITLE
Jar包冲突

### ISSUE THREAD

**Issue by lfift** [ofdrw/ofdrw#145]

**Comment by lfift** [comment]
![image](https://user-images.githubusercontent.com/31279478/148938080-26950558-1457-4cb8-bcc3-78fd16b4d142.png)
![image](https://user-images.githubusercontent.com/31279478/148938118-9da7db59-58bb-4b94-bcb2-2e957b8fd4bc.png)
![image](https://user-images.githubusercontent.com/31279478/148938148-3420c132-8ae4-451b-88de-aef1931bc6e4.png)
![image](https://user-images.githubusercontent.com/31279478/148938181-96a513f4-69d4-45dc-b3dd-a9e983179d22.png)
![image](https://user-images.githubusercontent.com/31279478/148938205-c104477e-be77-436b-a781-fdc87f4a368b.png)

**Comment by Trisia** [comment]
由于兼容性考虑，jar包冲突请自行排除解决。
