### ISSUE TITLE
ofd文件解压后超出100M异常

### ISSUE THREAD

**Issue by chouxiaozi** [ofdrw/ofdrw#147]
https://github.com/ofdrw/ofdrw/blob/774b5d4fa26ef42798ccf0cc56532ea3b95cbfd0/ofdrw-reader/src/main/java/org/ofdrw/reader/ZipUtil.java?_pjax=%23js-repo-pjax-container%2C%20div%5Bitemtype%3D%22http%3A%2F%2Fschema.org%2FSoftwareSourceCode%22%5D%20main%2C%20%5Bdata-pjax-container%5D#L40

请问这里加这个拦截的原因是什么，哪里有问题吗

**Comment by Trisia** [comment]
通过精心构造的ZIP文件可以使得内存OOM

**Comment by chouxiaozi** [comment]
看到代码了。。。精心构造的zip能发一下吗。长啥样子的

**Comment by Trisia** [comment]
@QAQtutu

**Comment by QAQtutu** [comment]
https://github.com/ofdrw/ofdrw/blob/774b5d4fa26ef42798ccf0cc56532ea3b95cbfd0/ofdrw-reader/src/test/resources/zip_boom.zip

**Comment by QAQtutu** [comment]
1mb文件可以解压出1G文件，理论上可以构造出一个压缩率趋近于无穷大的压缩文件。由于ofdrw的原理是解压文件到硬盘临时目录，所以存在硬盘被精心构造的zip占满的风险。详情可以搜索ZIP炸弹。

**Comment by chouxiaozi** [comment]
是不是可以通过检测压缩率的方式检测zip炸弹。
具体可以参考Apache-poi的 ZipSecureFile.setMinInflateRatio()方法

**Comment by QAQtutu** [comment]
可以，但问题在于压缩率不容易估测， 一个正常的小文件可能里面重复度也很高，一个极大的文件可能里面重复度很小。相比之下文件大小就比较容易估算。不管压缩率多少，都需要限制文件的大小以免占满磁盘。这里100MB限制之后会改成可配置的，根据系统处理文件的类型来自行估算。

**Comment by chouxiaozi** [comment]
有道理的！

最好在区分一下应用场景，zip炸弹就是恶意坏文件，检测到就应该报错。
但是正常文件就算再大，有正常的解压需求就走解压逻辑。

**Comment by Trisia** [comment]
1.17.9 修复
