### ISSUE TITLE
建议README.md QuickStart的demo要能正常运行

### ISSUE THREAD

**Issue by zavch** [ofdrw/ofdrw#153]
目前直接运行QuickStart的demo是会抛出NPE异常，原因是由于org.ofdrw.layout.OFDDoc的QFDoc(Path outpath）构造器对outPath的父目录是否存在做判断这里（161行~163行）：
```
// 当output不包含路径时，outPath.getParent()返回null，从而导致NPE，此处应做调整
if (!Files.exists(outPath.getParent())) {
          ...
}
```

**Comment by Trisia** [comment]
我个人认为父目录的创建是开发者的责任，

**Comment by zavch** [comment]
你好，我的意思是说父目录这里的判断未涵盖当path不包含路径分隔符的情况，当path不包含路径分隔符时，Path.getParent()返回的为null（即使该父目录存在），而Files.exists()参数不能为null，进而抛出NPE

**Comment by Trisia** [comment]
该问题已经解决，预计下个版本发布，发布时间待定。
