### ISSUE TITLE
能否支持等宽排列

### ISSUE THREAD

**Issue by blueelfgh** [ofdrw/ofdrw#155]
作者，您好：
        现在我需要实现一个这样的功能，客户端通过OCR将图片中的一行字，得出字符串和这行字的在图片里的宽和高，然后将这些数据传给服务端合成ofd，但是由于客户端没能识别出字体，导致合成处理的文字无法到达指定的宽度，请问有接口能使得框里的文字，进行等宽排列使得文字符号能够填满框吗？或者有另外的办法也能够实现让字体宽度填满框。效果如图片所示
![E3195B4174CE25D0CDA51C04CF5DED04](https://user-images.githubusercontent.com/2289047/159218112-f8f4dacf-3b89-480f-93b0-4f0e610b6200.jpg)

以下是我实现的代码：
                
                String text = (String) ((HashMap<String, Object>) textObject).get("text");
                double fontSize = (int) ((HashMap<String, Object>) textObject).get("fontSize");
                double textHeight = (int) ((HashMap<String, Object>) textObject).get("height");
                double textWidth = (int) ((HashMap<String, Object>) textObject).get("width");
                double x = (int) ((HashMap<String, Object>) textObject).get("x");
                double y = (int) ((HashMap<String, Object>) textObject).get("y");
                // 设置文本相关信息
                Paragraph p = new Paragraph(textWidth,textHeight).setFontSize(textHeight*0.75);
                p.setBorder(1d);    //TODO  调试使用
                p.add(text);
                p.setPosition(Position.Absolute).setX(x).setY(y);

                // 添加文本
                vPage.add(p);

**Comment by Trisia** [comment]
不支持
