### ISSUE TITLE
ofd转pdf缺失印章

### ISSUE THREAD

**Issue by jimmyhm20** [ofdrw/ofdrw#156]
ofd格式的发票，转换为pdf发票，不同的环境存在丢失印章。有的可以有的不行

**Comment by DLTech21** [comment]
不同环境是指服务器？

**Comment by jimmyhm20** [comment]
同一套代码，不同的服务器。

**Comment by DLTech21** [comment]
啥服务器不行？信创？

**Comment by jimmyhm20** [comment]
不是。我们自己本地的笔记本跑的程序，有的可以有的不行。很奇怪。

**Comment by DLTech21** [comment]
没有报错？

**Comment by jimmyhm20** [comment]
没有报错，就是会有一些字体忽略，转换也可以转换成功，就是红章没了。查看就是pdf软件。转换后，有章的会比无章的大几十k

**Comment by DLTech21** [comment]
同一个文件吗？

**Comment by jimmyhm20** [comment]
同一个文件。环境区别就是一个jdk版本是1.8.0_231 我是用的152 其他就是tomcat版本可能不太一样。

**Comment by DLTech21** [comment]
java环境一致试试

**Comment by MianMianChan** [comment]
印章中的字体太大导致重叠有遇到的吗？
![image](https://github.com/ofdrw/ofdrw/assets/80753589/9cf8559f-d242-4c26-8a8a-333dcd517463)
