### ISSUE TITLE
电子签章验证失败

### ISSUE THREAD

**Issue by zhougn18** [ofdrw/ofdrw#160]
try (OFDReader reader = new OFDReader(src);
             OFDValidator validator = new OFDValidator(reader)) {
            validator.setValidator(new SESV4ValidateContainer());
            validator.exeValidate();
            System.out.println(">> 验证通过");
        }这段代码执行验证失败
![image](https://user-images.githubusercontent.com/25735464/163667229-cbf28269-3b67-46d5-a2c1-811c824794f8.png)
但是 用数科ofd阅读器 
![image](https://user-images.githubusercontent.com/25735464/163667264-87fb6464-d215-4a9b-b333-c313817ab90e.png)
是能通过的   这是什么原因阿

**Comment by Trisia** [comment]
请提供OFD文件，可以发链接或到群里发送

**Comment by Trisia** [comment]
较长时间未响应，关闭。
