### ISSUE TITLE
请问有没有道友遇到了字体缺失的问题。

### ISSUE THREAD

**Issue by itknight** [ofdrw/ofdrw#169]
首先非常感谢该仓库作者，为我们读写`OFD`提供了便利。在使用过程中，通过`OFD`转`PDF`遇到了字体缺失的情况，本机还好，上了生产机CentOS以后，直接字体都没有了，如下图所示：
<img width="967" alt="image" src="https://user-images.githubusercontent.com/7972442/173985007-d973c43d-49de-4cd8-8655-be3c5496fd2c.png">
转换代码如下：
<img width="790" alt="image" src="https://user-images.githubusercontent.com/7972442/173985324-dda4df56-bb1e-4ac3-a513-29cea36e04d6.png">
<img width="725" alt="image" src="https://user-images.githubusercontent.com/7972442/173985399-775629fb-025a-434b-848d-26c26caaa85d.png">
<img width="574" alt="image" src="https://user-images.githubusercontent.com/7972442/173985465-dab90180-a85b-4b58-ac2c-7572a3b84ccc.png">
如下图为我的字体文件目录：
<img width="331" alt="image" src="https://user-images.githubusercontent.com/7972442/173985554-f4c46480-1e79-4b6f-bca5-17f993ff6701.png">

**Comment by Trisia** [comment]
字体问题暂无较好解决方案。

你可以把字体放到操作系统目录中，在程序启动时手动加载。

由于部分opentype缺少关键表，导致字体文件无法解析，ofdrw目前采用默认的宋体进行替换。

**Comment by yuanfangme** [comment]
fontloader的字体检索目前还存在问题：1.在不同系统、语言下会匹配不全，而找不到字体；2.某些字体由于版权不能被嵌入pdf

**Comment by ljegithub** [comment]
C:\Windows\TEMP\ofd-tmp-9052500436756058667\Doc_0\Res\font_18.ttf , Table os/2 does not  如何解决

**Comment by 344020353** [comment]
系统加载出来的都是英文字体，怎么才匹配得上呢，打开windows看字体也是中文的
![image](https://user-images.githubusercontent.com/6700402/216317752-e8902cf7-1416-45ee-a4d5-6b6c6916088d.png)
![image](https://user-images.githubusercontent.com/6700402/216317859-37055e11-4e8b-4248-9460-8f28103b1c87.png)

**Comment by Trisia** [comment]
2.0.5 修复
