### ISSUE TITLE
ofd文件加密后文件打不开，并且没有输入口令等提示

### ISSUE THREAD

**Issue by mafuchao** [ofdrw/ofdrw#171]
ofd文件加密后文件打不开，ofdrw中没有看到解密的方法，是否可以提供解密个方法

**Comment by DLTech21** [comment]
ofd加密后文件发来看看

**Comment by mafuchao** [comment]
打开加密后文件报不支持打开该格式文件
![image](https://user-images.githubusercontent.com/61139927/175869341-98e4b094-0f8b-4fa7-b773-abe679fc8314.png)

**Comment by mafuchao** [comment]
在 2022-06-27 13:40:39，"Donal" ***@***.***> 写道：

ofd加密后文件发来看看

**Comment by wangsm123** [comment]
我也遇到了这个问题，使用福析的不能打开，用了网页上的ofd.js也是打不开

**Comment by Trisia** [comment]
目前现有的阅读器暂无支持解密功能，加密功能于GMT0099 2020文件中描述。
