### ISSUE TITLE
ofd加密后的文件和原文件之间怎么对照，怎么知道原文件是哪个

### ISSUE THREAD

**Issue by mafuchao** [ofdrw/ofdrw#172]
一个原文件用同样的口令加密多次
1、如何知道加密后的文件是同一个
2、如何知道原文件和加密后的文件是同一个文件

**Comment by Trisia** [comment]
我认为文件加密不应该存在多次，文件加密本质是用户使用关键信息加密文件加密密钥（EK），如果访问者为多人，每个用户独立加密文件加密密钥（EK）。详见 [OFD加密协议](https://github.com/ofdrw/ofdrw/blob/master/ofdrw-crypto/doc/enc/README.md)

加密后文件不应该留有原文档信息，否则可以一定程度上认为泄露了文档内容，因此我认为非特殊情况应该不能够比对是否是同一个文件。
