### ISSUE TITLE
svg图片能作为图片资源引入吗

### ISSUE THREAD

**Issue by skycsky** [ofdrw/ofdrw#174]
try (OFDDoc ofdDoc = new OFDDoc(ofdPath)) {
      PageLayout pageLayout = ofdDoc.getPageLayout();
      VirtualPage vPage = new VirtualPage(pageLayout);
      Img imgDiv = new Img(pageLayout.getWidth(), pageLayout.getHeight(), Paths.get(imgPath).toAbsolutePath());

      double x = (pageLayout.getWidth() - imgDiv.getWidth()) / 2;
      double y = (pageLayout.getHeight() - imgDiv.getHeight()) / 2;
      imgDiv.setPosition(Position.Absolute).setX(x).setY(y);
      imgDiv.setBorder(0d);
      imgDiv.setPadding(0d);
      vPage.add(imgDiv);
      ofdDoc.addVPage(vPage);
}
这段代码没有报错，但是生成的ofd文件显示图片是花的
这个方式不行的话，有其他方式来加入svg图片吗？

**Comment by Trisia** [comment]
SVG这个可能需要手动构造了，目前Img对象暂时无法支持自定义类型的资源，你可以继承并重写Img对象，实现相关功能
