### ISSUE TITLE
USER.p12与ROOT.p12证书

### ISSUE THREAD

**Issue by acytee** [ofdrw/ofdrw#176]
### 源码有用到两个证书USER.p12与ROOT.p12，测试时有两个疑问，希望了解项目的帮忙解惑，谢谢！
* 我理解ROOT.p12应该是国家认证机构的ca证书，user.p12是需要客户自己提供给电子签名的实现平台？
* 使用keytool查看证书报错：keytool -v -list -keystore USER.p12  
 keytool错误: java.io.IOException: Invalid keystore format

**Comment by acytee** [comment]
[算是找到问题2报错原因：国密证书使用了自有的椭圆曲线，所以无法使用JDK自带的java.security解析证书](https://blog.csdn.net/qq_40806881/article/details/120524669)

**Comment by acytee** [comment]
[算是找到问题2报错原因：国密证书使用了自有的椭圆曲线，所以无法使用JDK自带的java.security解析证书](https://blog.csdn.net/qq_40806881/article/details/120524669)

**Comment by Trisia** [comment]
密码学相关部分不属于OFDRW项目范畴，请自行学习相关领域知识解决。

**Comment by roy19831015** [comment]
代码层面的支持可以参考工程利用bc库1.62版本的代码，至于keytool为何不支持，不在本工程讨论范围

**Comment by acytee** [comment]
* 我提的两个问题，咋就被关了，keytool问题前面我自己找到原因了，不清楚的码友可以看我发的链接，第一个问题有人了解么
