### ISSUE TITLE
如何理解ofd使用用户的私钥和公钥签章？

### ISSUE THREAD

**Issue by acytee** [ofdrw/ofdrw#177]
![image](https://user-images.githubusercontent.com/58213945/188106645-619af3d5-6095-4e79-b124-1b0dfb9d1955.png)
* 源码测试类这里用的用户私钥和公钥来签章不太明白，请教下了解的朋友，谢谢
* 个人理解公钥可以公开，存签章实现的平台上，但私钥是用户自己保存的，不可能给到签章实现平台保存或是通过网络传输给平台

**Comment by Trisia** [comment]
该问题属于密码行业范畴，不在该项目讨论范围内，关闭。
