### ISSUE TITLE
请问有没有道友遇到了字体缺失的问题1

### ISSUE THREAD

**Issue by 344020353** [ofdrw/ofdrw#179]
系统加载出来的都是英文字体，怎么才匹配得上呢，打开windows看字体也是中文的
![image](https://user-images.githubusercontent.com/6700402/216327975-2b1b1ef5-bd1b-41ce-b97a-27ec9afc40aa.png)
![image](https://user-images.githubusercontent.com/6700402/216328018-4ac03149-db05-4ebe-b33d-66d4d544cb01.png)

**Comment by Trisia** [comment]
2.0.5 fix
