### ISSUE TITLE
电子发票OFD文件转pdf后，右下角印章出现重影

### ISSUE THREAD

**Issue by savenYPF** [ofdrw/ofdrw#183]
![image](https://user-images.githubusercontent.com/49469765/224022398-9b0fc5ec-48ad-4e09-9d65-b4752d3150e8.png)

**Comment by DLTech21** [comment]
ofd发出来

**Comment by savenYPF** [comment]
[48.3 (2).pdf](https://github.com/ofdrw/ofdrw/files/10942002/48.3.2.pdf)
@DLTech21 github的富文本不支持传入ofd格式文件，我重命名为了pdf,你下载后改回.OFD格式

**Comment by savenYPF** [comment]
[44.34.PDF](https://github.com/ofdrw/ofdrw/files/10953035/44.34.PDF)
抱歉，上面的OFD文件虽然统样存在问题不过并非遇到此问题的源文件，出现两个章的是这张

**Comment by DLTech21** [comment]
打不开，可以发我邮箱 541815852@qq.com

**Comment by DLTech21** [comment]
打不开，可以发我邮箱 541815852@qq.com

**Comment by Trisia** [comment]
OFD转换PDF 功能，将进入长期维护状态，不再持续更新，若您有修复建议请提交PR。
