### ISSUE TITLE
pdf转ofd如何支持自定义字体

### ISSUE THREAD

**Issue by piers1202** [ofdrw/ofdrw#184]
你好，请问一下pdf转ofd可以支持使用自定义字体及大小吗？默认转换出来的文件字体与原pdf有较大差异

**Comment by Trisia** [comment]
请提供PDF文件。

**Comment by piers1202** [comment]
> 请提供PDF文件。
https://ptbox.obs.cn-east-3.myhuaweicloud.com/assets/033002000113_09014601.pdf
https://ptbox.obs.cn-east-3.myhuaweicloud.com/assets/convert.ofd
前者是我测试用的pdf文件，后者是转换后的文件。也不能指定成某种字体，原文件内容里有不同的字体。感谢！

**Comment by Trisia** [comment]
收到。

**Comment by Trisia** [comment]
该问题尚未能找到原因，若您对项目感兴趣可以尝试修复并提交PR。

**Comment by Trisia** [comment]
若只是添加字体你可以把字体文件放置到操作系统相关目录内，然后重启程序。

**Comment by piers1202** [comment]
> 若只是添加字体你可以把字体文件放置到操作系统相关目录内，然后重启程序。

好的，我这个场景还是不能指定成某一字体，因为原文件包含了不同的字体
