### ISSUE TITLE
OFD文件解析异常

### ISSUE THREAD

**Issue by Doneyzhu** [ofdrw/ofdrw#185]
```
<ofd:Document xmlns:ofd="http://www.ofdspec.org/2016">
	<ofd:CommonData>
		<ofd:MaxUnitID>6954</ofd:MaxUnitID>
		<ofd:PublicRes>PublicRes.xml</ofd:PublicRes>
		<ofd:TemplatePage ID="1" BaseLoc="Tpls/Tpl_0/Content.xml"/>
		<ofd:DocumentRes>DocumentRes.xml</ofd:DocumentRes>
	</ofd:CommonData>
	<ofd:Pages>
		<ofd:Page ID="61" BaseLoc="Pages/Page_0/Content.xml"/>
	</ofd:Pages>

	<ofd:CustomTags>Tags/CustomTags.xml</ofd:CustomTags>
	<ofd:Annotations>Annots/Annotations.xml</ofd:Annotations>
</ofd:Document>
```
某些电子发票 Document.xml文件 CommonData标签下没有PageArea标签 
导致 DLOFDReader类 下面getPageBox方法
documentBox = document.getCommonData().getPageArea().getPhysicalBox();
抛出异常

**Comment by Trisia** [comment]
![image](https://user-images.githubusercontent.com/17817790/227708734-04b488da-5d65-4d71-8e5a-a104da6efdab.png)

**Comment by Doneyzhu** [comment]
> ![image](https://user-images.githubusercontent.com/17817790/227708734-04b488da-5d65-4d71-8e5a-a104da6efdab.png)

但是没有该标签，文件也是可用的。
具体文件如下：
[青岛餐饮11.zip](https://github.com/ofdrw/ofdrw/files/11074158/11.zip)

**Comment by Trisia** [comment]
为了保证文件的正确性，原则上不对非标准进行兼容。
