### ISSUE TITLE
ofdsign报错：no such algorithm: 1.2.156.10197.1.401.2 for provider BC

### ISSUE THREAD

**Issue by ouyang7923** [ofdrw/ofdrw#192]
使用EC或SM2，exeSign 写入签名正常；exeValidate 验签报错 no such algorithm: 1.2.156.10197.1.401.2 for provider BC。很是奇怪，请问如何解决

**Comment by Trisia** [comment]
OFDRW的几个验签容器仅供仓考，若需要个性化的验签需求，请实现 `SignedDataValidateContainer`接口。
