### ISSUE TITLE
导出是否考虑增加OutputStream参数支持？

### ISSUE THREAD

**Issue by xiaobaogeit** [ofdrw/ofdrw#193]
比如直接对接的`对象存储OSS`情况，以及`OutputStream`可扩展性更强些

**Comment by Trisia** [comment]
不支持，由于OFD是 ZIP格式文件特性，在文件操作时为了简化程序逻辑，采用打开时解压，关闭时压缩的策略，无论如何都需要一个具体的路径用于存储压缩后的文件，即便的是临时文件。

OutputStream 你可以直接解析路径文件获得。
