### ISSUE TITLE
两个ofd中使用不通的模板，合并后，只剩下一个模板，导致合并后的显示不正确

### ISSUE THREAD

**Issue by juluren** [ofdrw/ofdrw#197]
OFDMerger ofdMerger = new OFDMerger(dst);
			Path d2Path = Paths.get(
					"C:\\Users\\julur\\Downloads\\deposit_note_2023-06-06_44237.47_ _20231570254228.ofd");
			Path d1Path = Paths.get(
					"C:\\Users\\julur\\Downloads\\payment_note_2023-06-06_17307478.05_913275000018_20231570362098.ofd");
			ofdMerger.add(d1Path);
			ofdMerger.add(d2Path);
			ofdMerger.close();

两个ofd中使用不通的模板，合并后，只剩下一个模板，导致合并后的显示不正确

**Comment by Trisia** [comment]
#198
