### ISSUE TITLE
ofd文档合并问题

### ISSUE THREAD

**Issue by wang1112223333** [ofdrw/ofdrw#198]
使用多个不同的ofd模板生成的ofd文件，合并后的文件会以第一个模板的样式为标准，而不是多个不同的模板样式，合并后的文件会失去原有样式。

**Comment by Trisia** [comment]
文档迁移只保证 多个文档进行 页面层级的组合，迁移的单元是页面，不同文档的模板按照逻辑只属于各自页面互不影响。
