### ISSUE TITLE
由pdf转换的ofd 字体变粗 变黑

### ISSUE THREAD

**Issue by Insua** [ofdrw/ofdrw#201]
这是原始的pdf文件
![pdf](https://storage-cdn.mifengchengshi.com/sign/pdf.png)
这是转换后的ofd文件
![ofd](https://storage-cdn.mifengchengshi.com/sign/ofd.png)

请问这种情况怎么处理呢

**Comment by Trisia** [comment]
已于2.0.9 修复

**Comment by Insua** [comment]
🐮 后续期待更新为font + 字符的模式
