### ISSUE TITLE
在windows环境下运行，转换文件报错zipexception

### ISSUE THREAD

**Issue by WhisperwindBill** [ofdrw/ofdrw#207]
java.util.zip.ZipException: invalid entry compressed size (expected 1423 but got 1419 bytes)
在windows环境下运行发生如上错误，多个文件测试结果均同
        ByteArrayOutputStream byteArrayOutputStream=new ByteArrayOutputStream();
        HTMLExporter exporter=new HTMLExporter(stream,byteArrayOutputStream);
        exporter.export();
        return new String(byteArrayOutputStream.toByteArray(),"UTF-8");
转换代码如上

**Comment by Trisia** [comment]
提供文件

该问题是由于压缩文件格式问题导致

**Comment by Trisia** [comment]
无响应关闭
