### ISSUE TITLE
pdf 转ofd 部分下划线和表格消失

### ISSUE THREAD

**Issue by WifiStop** [ofdrw/ofdrw#212]

**Comment by Trisia** [comment]
请附带问题文件

**Comment by wong1998** [comment]
就是原word中的“_”字符如果做下划线是可以显示的，但是如果是很长的空格，加上在word中选择为下划线，如下所示。
![image](https://github.com/ofdrw/ofdrw/assets/50826229/f47d67e1-b648-4298-b289-59d0c83ad505)
word转的pdf再转ofd后，这样的下划线是不显示的

**Comment by Trisia** [comment]
请在附带中附带 问题文件

**Comment by Trisia** [comment]
超时无响应。
