### ISSUE TITLE
ST_Array#getInt 方法无法将浮点数转换为整数

### ISSUE THREAD

**Issue by Gardelll** [ofdrw/ofdrw#221]
ST_Array#getInt 主要用在颜色空间和字形索引上，但是由于一些实现默认将颜色格式化为浮点数格式，比如白色会表示为 "255.0 255.0 255.0"
OFDRW 目前无法兼容这种格式。

**Comment by Trisia** [comment]
ST_Array 作为底层方法，应该直接和准确的返回指定类型，对于错误数值类型不应采取兼容，兼容行为应该由调用者负责。

**Comment by Gardelll** [comment]
我修改了代码，仅在转换颜色时兼容浮点数
