### ISSUE TITLE
2.1.1版本渲染注释的时候会出现问题

### ISSUE THREAD

**Issue by FanQinFred** [ofdrw/ofdrw#229]
OFD转PDF模块函数：
private void writeAnnoAppearance(ResourceManage resMgt,
                                     PdfCanvas pdfCanvas,
                                     PageInfo pageInfo,
                                     List<AnnotionEntity> annotionEntities,
                                     ST_Box box) {
        try{
            String pageId = pageInfo.getId().toString();
            for (AnnotionEntity annotionEntity : annotionEntities) {
                List<Annot> annotList = annotionEntity.getAnnots();
                if (annotList == null) {
                    continue;
                }
                if (!pageId.equalsIgnoreCase(annotionEntity.getPageId())) {
                    continue;
                }
                for (Annot annot : annotList) {
                    System.out.println(annot.toString());
                    System.out.println(annot.getAppearance().toString());
                    List<PageBlockType> pageBlockTypeList = annot.getAppearance().getPageBlocks();
                    //注释的boundary
                    ST_Box annotBox = annot.getAppearance().getBoundary();
                    writePageBlock(resMgt, pdfCanvas, box, null, pageBlockTypeList, null, annotBox, null, null, null);
                }
            }
        }catch (Exception e){
            e.printStackTrace();
        }
    }

上述代码中List<PageBlockType> pageBlockTypeList = annot.getAppearance().getPageBlocks();会返回NULL。目前解决方案还在分析中。
导致问题：无法使用字体。

**Comment by FanQinFred** [comment]
`    private void writeAnnoAppearance(ResourceManage resMgt,
                                     PdfCanvas pdfCanvas,
                                     PageInfo pageInfo,
                                     List<AnnotionEntity> annotionEntities,
                                     ST_Box box) throws IOException {
        String pageId = pageInfo.getId().toString();
        for (AnnotionEntity annotionEntity : annotionEntities) {
            List<Annot> annotList = annotionEntity.getAnnots();
            if (annotList == null) {
                continue;
            }
            if (!pageId.equalsIgnoreCase(annotionEntity.getPageId())) {
                continue;
            }
            for (Annot annot : annotList) {
                if(annot.getAppearance()!=null){
                    List<PageBlockType> pageBlockTypeList = annot.getAppearance().getPageBlocks();
                    //注释的boundary
                    ST_Box annotBox = annot.getAppearance().getBoundary();
                    writePageBlock(resMgt, pdfCanvas, box, null, pageBlockTypeList, null, annotBox, null, null, null);
                }
            }
        }
    }`
先简单的判断是否为null吧。

**Comment by Trisia** [comment]
fixed in 2.2.3
