### ISSUE TITLE
导出pdf字体不可用时，logger出现NPE

### ISSUE THREAD

**Issue by ymlisoft** [ofdrw/ofdrw#230]
![image](https://github.com/ofdrw/ofdrw/assets/9900158/616a986a-3b7f-4b2d-bc61-7aae82a2ea79)

![image](https://github.com/ofdrw/ofdrw/assets/9900158/9bed5f6c-66a2-4422-a967-47e3c157dc43)

**Comment by ymlisoft** [comment]
Version: 2.2.3

**Comment by Trisia** [comment]
9d1b35521e7be4c1aa126f09c8af2ca2963f082d
