### ISSUE TITLE
pdf转ofd，生成的ofd文件过大

### ISSUE THREAD

**Issue by N1ckeyQu** [ofdrw/ofdrw#232]
hello，我使用的是2.2.3版本的ofdrw

目前使用ofdrw全量转换3.35 MB的pdf，生成的ofd文件大小为97.8 MB，这个文件有些过大了，但我不知道要如何压缩这个ofd文件。我尝试从ChatGPT中寻找答案，它告诉我可以通过ImageUtils.compress(ofdFile, 0.8f);也就是压缩文件中图片质量的方式，但我在ImageUtils中没有找到此方法，想问下还有没有其它的方法可以压缩生成的ofd文件

**Comment by N1ckeyQu** [comment]
这是我使用的pdf文件

**Comment by DLTech21** [comment]
这个与图片关系不大，主要是文字在转换到ofd是线条元素
