### ISSUE TITLE
用自定义字体，段落添加行间距后，段落显示不全

### ISSUE THREAD

**Issue by znxd-wh** [ofdrw/ofdrw#233]
使用外部字体，同时段落添加行间距后，文字会显示不全。
有意思的是这个行间距用1.5,2.0都没事，1.9就不中了。

import com.alibaba.fastjson.JSONArray;
import org.ofdrw.font.Font;
import org.ofdrw.layout.OFDDoc;
import org.ofdrw.layout.PageLayout;
import org.ofdrw.layout.element.*;

import java.io.IOException;
import java.nio.file.Path;
import java.nio.file.Paths;

public class TextTest {
    public static void main(String[] args) throws IOException {

        String pathStr = "E:/text.ofd";
        String textTitle = "“A国者”FKDDZD影像解译报告";
        JSONArray paragraphArr = new JSONArray();
        String p1 = "KJJD13718空军基地位于日本鹿児島県鹿屋市地区西南部(130.8381°E，31.3731°N)，占地面积10.52平方千米。";
        String p2 = "根据2020年11月18日影像智能识别发现，KJJD13718空军基地主要设施包括跑道3条,其中一条跑道长1616.54米、宽51.84米、方向81°-261°，一条跑道长2253.4米、宽68.83米、方向81°-261°，一条跑道长404.45米、宽47.2米、方向81°-261°；滑行道1条,滑行道长1924.95米、宽102.44米、方向102°-282°；联络道7条；集体停机坪1处,总面积约382705.25平方米；机库10栋；油库1处，其中半地下油库1个。";
        String p3 = "卫星监测时，基地停驻：反潜巡逻机5架,其中P-1 4架,P-3C 1架；直升机1架,其中TH-135 1架；其他飞机3架。";
        paragraphArr.add(p1);
        paragraphArr.add(p2);
        paragraphArr.add(p3);
        String uploadFilder = "E:/";
        Double multiple = 1.9;//1.5 2.0都没问题，用1.9第二段显示不全
        generateTextOFD(pathStr,textTitle,paragraphArr,uploadFilder,multiple);
    }
    public static void generateTextOFD(String pathStr, String titleStr, JSONArray paragraphArr, String uploadFilder, Double multiple) throws IOException, IOException {
        //系统注入字体
        Path fontFile = Paths.get(uploadFilder, "FZXBSJW.ttf");
        Double titleFontSize = 7.76;
        Double pFontSize = 5.64;

        Path path = Paths.get(pathStr).toAbsolutePath();
        try (OFDDoc ofdDoc = new OFDDoc(path)) {
            //ofd注入字体
            Font font = new Font("FZXBSJW", "FZXBSJW", fontFile);
            PageLayout pageLayOut = PageLayout.A4();
            pageLayOut.setMarginLeft(0.0);
            pageLayOut.setMarginRight(0.0);
            pageLayOut.setMarginTop(10.0);
            ofdDoc.setDefaultPageLayout(pageLayOut);

            Span report = new Span("报告：").setBold(false).setFontSize(6d);
            Paragraph pReport = new Paragraph().add(report);
            pReport.setMarginLeft(10.0);
            pReport.setMarginTop(0.0);
            ofdDoc.add(pReport);

            Span title = new Span(titleStr).setBold(true).setFontSize(titleFontSize).setFont(font);
            Paragraph p = new Paragraph().add(title);
            p.setMargin(2.0);
            p.setFloat(AFloat.center);
            p.setLineSpace(titleFontSize * multiple);
            ofdDoc.add(p);

            for (int i = 0; i < paragraphArr.size(); i++) {
                Font font1 = new Font("FangSong", "FangSong");
                String contentStr = paragraphArr.getString(i);
                Span content = new Span(contentStr).setFontSize(pFontSize).setFont(font1);
                Paragraph p1 = new Paragraph().add(content).setFirstLineIndent(2).setMargin(2.0).setMarginLeft(15.0).setMarginRight(15.0);
                p1.setLineSpace(pFontSize * multiple);
                ofdDoc.add(p1);
            }
        }
    }
}
[测试程序和字体.zip](https://github.com/ofdrw/ofdrw/files/13725648/default.zip)

**Comment by znxd-wh** [comment]
补充一下，linux中，行间距用1.5也不中，linux是ubantu

**Comment by Trisia** [comment]
fixed in 4d108f73b7240ad0d0b0aba80578635e237eebae
