### ISSUE TITLE
我本地环境编辑回填数据正常，但是部署到服务器之后一直回填不上

### ISSUE THREAD

**Issue by heguojuns** [ofdrw/ofdrw#236]
新生成的文件新加了这几个标签，没有具体的内容。我在本地测试是有具体内容的。
<ofd:Layer ID="449" Type="Body"/>
 <ofd:Layer ID="451" Type="Body"/>
<ofd:Layer ID="453" Type="Body"/>
方法调用需要的参数都是有的
`
private static void addParagraph(AdditionVPage avPage, double x, double y, String[] values, int i2, double v) {
        Paragraph p1 = new Paragraph(values[i2], 6d, new Font("FangSong_GB2312","FangSong_GB2312"))
                .setPosition(Position.Absolute).setX(x).setY(y).setWidth(v);
        avPage.add(p1);
    }
`
排查了字体文件都没有问题，找不到原因了。。

**Comment by Trisia** [comment]
请提供可运行main代码以及故障文件

**Comment by heguojuns** [comment]
麒麟V10操作系统安装的openjdk导致字体宽度拿不到，退出了OFD编辑逻辑，换成华为的毕昇jdk之后正常了。
![image](https://github.com/ofdrw/ofdrw/assets/35210192/5ebdf3f6-a4c7-4143-b888-61e13be7b21f)
![image](https://github.com/ofdrw/ofdrw/assets/35210192/43cab838-b3bf-4155-a894-96c8e8c93d81)
