### ISSUE TITLE
默认字库加载异常

### ISSUE THREAD

**Issue by flyingmousee** [ofdrw/ofdrw#238]
<img width="561" alt="EnvFont" src="https://github.com/ofdrw/ofdrw/assets/38202119/b9859996-ff43-4e15-9db2-ca5df4c9c2f2">
EnvFont.java中将系统字库缓存至fMap时key值作了小写处理，设置默认字库时，若[宋体]不存在，后续[SimSun]、[MicrosoftYaHei]、[STHeiti-Light]、[Times New Roman]等字体由于大小写敏感，均无法从缓存中正常加载。

**Comment by Trisia** [comment]
see c66f866a80554f1f0362e8f607d9cdeacf0758b0
