### ISSUE TITLE
OFD 转 PDF 后文件大小由 800KB 变为 8M

### ISSUE THREAD

**Issue by jujianfei** [ofdrw/ofdrw#240]
背景描述：我需要将一个带有 jpeg 图片的 ofd 转为 pdf，转换后，800kb 的 ofd 变为 8M 的 pdf。
分析结论：现有代码中，处理 jpeg 图片时，默认使用了 FlateDecode 过滤器，应使用 DCT_DECODE 过滤器。

![问题截图](https://github.com/ofdrw/ofdrw/assets/24663679/5a77aa5f-5c53-49ee-8d01-de58d887bfd3)

**Comment by jujianfei** [comment]
> 若你有好的建议或意见，请提交 Pull request

好的

**Comment by Trisia** [comment]
ref #242
