### ISSUE TITLE
请问如何在签章时设置时间戳

### ISSUE THREAD

**Issue by zhangxiao10** [ofdrw/ofdrw#241]

**Comment by Trisia** [comment]
时间戳由电子签章实现，ofdrw聚焦于OFD文档本身

**Comment by zhangxiao10** [comment]
TimeStampHook，麻烦问下签章时，这个属性如何使用

**Comment by zhangxiao10** [comment]
> 时间戳由电子签章实现，ofdrw聚焦于OFD文档本身


TimeStampHook，麻烦问下签章时，这个属性如何使用

**Comment by zhangxiao10** [comment]
> 时间戳由电子签章实现，ofdrw聚焦于OFD文档本身


TimeStampHook，麻烦问下签章时，这个属性如何使用
