### ISSUE TITLE
多个pdf文件合并后，原有水印丢失（文字水印、图片水印均如此）

### ISSUE THREAD

**Issue by zhangzhen1979** [ofdrw/ofdrw#245]
代码如下
                                // 声明OFD合并对象
                                File fileTemp = new File(fileOutSingle.toPath() + "_merger.ofd");
                                try (OFDMerger ofdMerger = new OFDMerger(fileTemp.toPath())) {
                                    ofdMerger.add(fileOutSingle.toPath());
                                    ofdMerger.add(fileBlank.toPath());
                                }

fileOutSingle这个文件是有水印的，合并之后的新文件，就没有水印了。
这个怎么处理？

**Comment by Trisia** [comment]
提供源文件和可运行的测试用例。

**Comment by zhangzhen1979** [comment]
[merger.zip](https://github.com/ofdrw/ofdrw/files/14455860/merger.zip)

**Comment by Trisia** [comment]
水印迁移将于 2.2.8支持
