### ISSUE TITLE
横向PDF转换OFD时，会出现页面横纵判断错误

### ISSUE THREAD

**Issue by zhangzhen1979** [ofdrw/ofdrw#246]
修改org.ofdrw.converter.ofdconverter.PDFConverter中convert方法，修改如下内容（160行）：
<img width="499" alt="微信图片_20240304183147" src="https://github.com/ofdrw/ofdrw/assets/38685517/d4642779-cede-4c46-bbd1-44e61732c4a4">

                PDPage page = pdfDoc.getPage(index);
                PDRectangle pdfPageSize = page.getBBox();

                int rotation = page.getRotation();

                float width = pdfPageSize.getWidth();
                float height = pdfPageSize.getHeight();

                if (rotation == 90 || rotation == 270){
                    float tmp = width;
                    width = height;
                    height = tmp;
                }

                // 将PDF页面尺寸缩放至OFD尺寸
                OFDPageGraphics2D ofdPageG2d = ofdDoc.newPage(width / uuPmm, height/ uuPmm);

**Comment by zhangzhen1979** [comment]
测试用PDF如下
[Uploading xbrl-001.pdf…]()

**Comment by zhangzhen1979** [comment]
已提交 Pull requests

**Comment by Trisia** [comment]
请在提交中附带一个示例文档已验证代码有效性。

**Comment by zhangzhen1979** [comment]
[xbrl-001.zip](https://github.com/ofdrw/ofdrw/files/14492856/xbrl-001.zip)

**Comment by Trisia** [comment]
该问题将于下个版本修复。
