### ISSUE TITLE
想问一下这个ofd转换器满足ofd/a的标准吗？可不可以将其他文档直接转换成ofd/a格式？

### ISSUE THREAD

**Issue by jimi190** [ofdrw/ofdrw#253]

**Comment by Trisia** [comment]
目前ofdrw的装换模块使用graphic2d 的方式进行转换，过程将丢弃所有PDF中的内嵌字体，并将文字转换为矢量路径。
ofd/a 你可以自己对 核查是否符合ofd/a标准
