### ISSUE TITLE
有没有可能将 itext 依赖换成 OpenPDF 依赖，以避免 AGPL3.0 License 的问题

### ISSUE THREAD

**Issue by mingfer** [ofdrw/ofdrw#256]
OpenPDF 是基于 iText 4.x 版本（MPL和LGPL双许可协议）fork。
参见：
https://github.com/LibrePDF/OpenPDF/

**Comment by Trisia** [comment]
项目内已经集成PDFBox实现

**Comment by mingfer** [comment]
> 项目内已经集成PDFBox实现

但是目前就 ofdrw-converter 模块来说，基于 PDFBox 的 OFD 转换 PDF 的实现存在两个问题：

* PDFBox 不支持残缺的字体
* PDFBox 实现的转换器也是用到了 itext 的接口 com/itextpdf/kernel/colors/Color
![image](https://github.com/ofdrw/ofdrw/assets/46556397/9091e9f9-fe28-417c-885e-7332bb808b99)

**Comment by mingfer** [comment]
@Trisia  我发现上面的报错是因为使用的 PdfBoxMaker 使用了 org.ofdrw.converter.utils.CommonUtil，然后这里面有个弃用的方法 convertOfdColor 使用到了 iText 的依赖。这个方法实际没被任何方法使用，所以删除这个方法就好了。
![image](https://github.com/ofdrw/ofdrw/assets/46556397/5af9bc3e-8497-492f-aa52-686511ea312f)

**Comment by mingfer** [comment]
@Trisia 关于 PDFBox 不支持残缺的字体，我想到的解决方案是：在 org.ofdrw.converter.PdfboxMaker#loadFont 方法提前对获取的字体进行判断，如果字体中没有 os2 或 post，就获取一个默认字体，然后将默认字体中的 os2 或 post 复制给残缺字体。这个方案测试可行。
![image](https://github.com/ofdrw/ofdrw/assets/46556397/b1f1191f-247c-4f1f-95c0-928a1396a4ce)

**Comment by Trisia** [comment]
> 使用的 PdfBoxMaker 使用了 org.ofdrw.converter.utils.CommonUtil，然后这里面有个

为保证软件兼容性，ofdrw原则上不会删除任何已经暴露的public内容。

**Comment by Trisia** [comment]
> @Trisia 关于 PDFBox 不支持残缺的字体，我想到的解决方案是：在 org.ofdrw.converter.PdfboxMaker#loadFont 方法提前对获取的字体进行判断，如果字体中没有 os2 或 post，就获取一个默认字体，然后将默认字体中的 os2 或 post 复制给残缺字体。这个方案测试可行。 ![image](https://private-user-images.githubusercontent.com/46556397/332650506-b1f1191f-247c-4f1f-95c0-928a1396a4ce.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY0MzA5OTYsIm5iZiI6MTcxNjQzMDY5NiwicGF0aCI6Ii80NjU1NjM5Ny8zMzI2NTA1MDYtYjFmMTE5MWYtMjQ3Yy00ZjFmLTk1YzAtOTI4YTEzOTZhNGNlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIzVDAyMTgxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNmYjRlOTg5OWFkNWIyNGQxZTExZWVmMTM1MTM4YTI4OTQ5YWVjNDc2MDQ0Yzc3YmYwZWU2NDEzMDg2OTZkOTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.oCnxWQXmmmwXrs-MCQa9KX3MHrbtOA7RurdUHDgIH2M)

os/2 与 post 不同字体可能不一样，使用默认字体中的表可能不匹配造成额外的问题，这两个表是历史原因用于兼容老旧字体解析程序并且也非关键表。
