### ISSUE TITLE
本地环境和部署环境，换行效果不一致

### ISSUE THREAD

**Issue by fqjedu** [ofdrw/ofdrw#258]
我在本地（windows）插入文字到 ofd 中可以正常换行，但是把程序打包放到服务器（linux）上面去的话插入文字就换行不了了。
![image](https://github.com/ofdrw/ofdrw/assets/86455835/48333c8b-a6a9-461c-aa0b-ca861a5168b5)

**Comment by fqjedu** [comment]
我发现问题其实不是没换行，而是所有字体都挤在一起了

**Comment by Trisia** [comment]
服务器缺字体

**Comment by fqjedu** [comment]
已经解决，最终原因是因为我的程序跑在docker中，字体放在了宿主机，没有同步到docker容器

**Comment by fun-li** [comment]
> 我发现问题其实不是没换行，而是所有字体都挤在一起了

我也是这个问题 ，但是我把本地字体同步到容器后还是不行，大佬有解决方案吗
