### ISSUE TITLE
parseSES_SignatureVersion 方法中使用ASN1Sequence.getInstance获取SignedValue.dat 会报错

### ISSUE THREAD

**Issue by hhwoshi77** [ofdrw/ofdrw#260]
经测试  使用ASN1Sequence.getInstance() 读取某类签章信息
会报
java.lang.RuntimeException: java.lang.IllegalArgumentException: failed to construct sequence from byte[]: Extra data detected in stream
异常
![Snipaste_2024-05-20_16-06-45](https://github.com/ofdrw/ofdrw/assets/86900889/6afe344b-e1ff-466c-9cb0-04f73d1426c3)

改用 
asn1InputStream = new ASN1InputStream(Files.newInputStream(batPath));
            ASN1Primitive asn1Primitive = asn1InputStream.readObject();
            if (asn1Primitive instanceof ASN1Sequence) {
                seq = (ASN1Sequence) asn1Primitive;
            }else {
                seq = null;
            }
能正常获取ASN1Sequence对象

**Comment by Trisia** [comment]
parseSES_SignatureVersion 只接受 提供DER编码字节序列、ASN1Sequence
