### ISSUE TITLE
cell渲染问题

### ISSUE THREAD

**Issue by hanxy1128** [ofdrw/ofdrw#264]
cell的padding在渲染是会影响cell的宽度，但width的值不影响，如图，绝对定位时第二个的x坐标是第一个的x坐标+width，修改cell的paddingleft和right会影响重叠面积
![05515df61f4475ffd67ac9a0e5c627e9](https://github.com/ofdrw/ofdrw/assets/109366377/b04069f1-bdeb-49ea-bdee-a0923da5a2bf)
padding设置为0后，还会有少许重叠，还未发现原因
![60469642700153f3eaec56994a7085ec](https://github.com/ofdrw/ofdrw/assets/109366377/b33f64a8-b9a5-4b96-abfa-e8387a378fec)

**Comment by Trisia** [comment]
https://github.com/ofdrw/ofdrw/blob/master/ofdrw-layout/doc/cell/%E7%9B%92%E5%BC%8F%E6%A8%A1%E5%9E%8B.png
