### ISSUE TITLE
使用疑问

### ISSUE THREAD

**Issue by hanxy1128** [ofdrw/ofdrw#269]
请问目前支持修改一个已存在的ofd文件的文本内容，图片，水印吗？或者把已存在的ofd文件的内容全部读取出来，修改后生成新的ofd文件。可以的话，请问在哪里有测试用例，这块没找到

**Comment by Trisia** [comment]
OFD是板式文档

**Comment by hanxy1128** [comment]
我看OFD转PDF的功能是将OFD中所有元素全部获取到，然后一个个绘制到PDF中。如果想要在OFD指定区域贴一张二维码，是不是也只能通过类似的方式，将sourceOFD文档通过绝对定位绘制到targetOFD文档中，然后再绘制新增的二维码图片
