### ISSUE TITLE
AreaHolderBlock相关

### ISSUE THREAD

**Issue by hanxy1128** [ofdrw/ofdrw#274]
您好，我已选择最新发布版本的源代码编译，AreaHolderBlock可以正常使用，但是最近新增的Line，Span等相关的更新就无法使用了，请问有什么办法解决吗

**Comment by Trisia** [comment]
master分支可能处于开发中，部分功能无法正常使用，若需要源码编译请使用tag版本

**Comment by hanxy1128** [comment]
2.3.0版本的AreaHolderBlock无法正常使用，如果AreaHolderBlock相关功能开发周期较长是否可以先拉一个AreaHolderBlock和Line，Span等相关的更新都能使用的源码分支

**Comment by hanxy1128** [comment]
弄错了，maven没自动刷新，2.3.0的AreaHolderBlock可以正常使用
