### ISSUE TITLE
AreaHolderBlock使用反馈

### ISSUE THREAD

**Issue by hanxy1128** [ofdrw/ofdrw#276]
绘制ofd的时候，需要在每页的固定位置绘制固定的内容，比如二维码或者文件编号。此时每页都需要放一个AreaHolderBlock。这种场景目前可以通过开发人员自定义一个名称规则来解决，比如bh+页码。最好能每个页面的AreaHolderBlock的名称都一样，在填充的时候把所有名称相同的AreaHolderBlock填充相同的内容。

**Comment by Trisia** [comment]
从设计的角度来说，AreaHolderBlocks.xml中的应具有唯一的标识符进行区分。

目前 区域占位区块 的名称也可由开发者指定，具体应用场景应由开发者调整适应。

**Comment by hanxy1128** [comment]
感觉唯一标识可以理解为业务的唯一标识，表示同一业务的区域使用同一标识。或者用name和tag来区分xml唯一标识和业务唯一标识，通过tag可以批量填充相同内容

**Comment by Trisia** [comment]
ofdrw作为基础工具库仅提供满足应用需求的文档操作功能，不会干预具体业务和应用场景。
