### ISSUE TITLE
文本相关

### ISSUE THREAD

**Issue by hanxy1128** [ofdrw/ofdrw#277]
OFD用于文书的场景比较多，希望，。！等标点符号不要出现的行首。希望图示句号出现在上一个行末。
![image](https://github.com/ofdrw/ofdrw/assets/109366377/d3e1a5b9-dde7-4d1a-a63d-d1a9c85abf13)

**Comment by Trisia** [comment]
对于解析器任何字体文件中出现的文字都一致处理，若你有更好的解决方案，请提供PR。

**Comment by hanxy1128** [comment]
我目前的方案是在TxtLineBlock中增加是否开启标点符号不出现在行首的开关，开启情况下载tryAdd和trySplitAdd两个方法中判断一下，如果下一个如果下一个字符是标点符号就直接放在同一行，您看这个方案是否可行。可行的话，我抽空尝试改一下，或者有没有更好的方案

**Comment by Trisia** [comment]
该方式可能导致字符溢出设定区域。

建议计算方案如下：

1. 增设开关，开启状态执行行末标点处理。
2. 若下一个字符为标点符号（全角/半角），且无有效空间容纳该字符，进入处理流程。
3. 标点前字符 与 符号 移动到下一行。
4. 若移动至下一行 字符 与 符号的总计空间大于可用空间，则舍弃字符（防止解析器无限循环）。

注意：
- 该切分方案需要考虑span是否可以切分
- 需要考虑Paragraph、Span都增设相应开关参数用于控制。
