### ISSUE TITLE
文本胖瘦属性

### ISSUE THREAD

**Issue by hanxy1128** [ofdrw/ofdrw#280]
你好，目前一段文字是这个效果
![98aca3b82ee90a4bbe253dcf95a9fe5b](https://github.com/ofdrw/ofdrw/assets/109366377/aec58ccc-a556-4fd8-abe6-caf27964a1a6)
如果想要字体不变，但是把文字变瘦，请问您有什么思路吗？
![3ad7524c6a395a528ffc1fa8594b66c1](https://github.com/ofdrw/ofdrw/assets/109366377/7059e804-f293-4754-82d8-c72f5910ee0a)

**Comment by Trisia** [comment]
使用Canvas的变换矩阵
