### ISSUE TITLE
导出OFD文件指定页码内容为新的OFD文件

### ISSUE THREAD

**Issue by hanxy1128** [ofdrw/ofdrw#284]
想要将OFD文件中部分页码导出来生成新的OFD文件，新的OFD文件中的内容不是图片，而是真实的OFD文档，我没找到这个工具，麻烦指导一下怎么实现，我尝试做一下

**Comment by Trisia** [comment]
[https://github.com/ofdrw/ofdrw/tree/master/ofdrw-tool](https://github.com/ofdrw/ofdrw/tree/master/ofdrw-tool)

**Comment by hanxy1128** [comment]
看到了，ofdMerger.add方法可以增加一个文件流的重载吗？生产环境中，原文件正常都不是在本地文件系统，基本在oss、minio这些文件服务器中，需要通过流获取。现在需要先下载下来

**Comment by Trisia** [comment]
不支持

**Comment by hanxy1128** [comment]
好的，此考虑主要是下载到本地会有再读取性能会稍微低点，直接用流的话，可以让使用人员自行维护流的关闭，关闭流也是常规操作了

**Comment by Trisia** [comment]
本质上流操作与下载到本地操作无任何区别。
