### ISSUE TITLE
OFD解析问题

### ISSUE THREAD

**Issue by hanxy1128** [ofdrw/ofdrw#293]
通过别的软件生成的OFD文件可以正常打开，使用OFDRW包将OFD转png时会报错。解压ofd后发现page文件夹如下图。应该是Page_后面不是数字导致报错，不知道这个能不能兼容
<img width="371" alt="262a4f133f5e8c45264b95723ce9d9b" src="https://github.com/user-attachments/assets/78d4216c-06a7-48bf-9dba-98b067bf5c79">

**Comment by Trisia** [comment]
请提供文件

**Comment by hanxy1128** [comment]
[test.zip](https://github.com/user-attachments/files/16656326/test.zip)

**Comment by Trisia** [comment]
提供main函数最简单的错误调用代码

**Comment by hanxy1128** [comment]
public void getPageNum(InputStream is) {
        try (OFDReader reader = new OFDReader(is)) {
            System.out.println(reader.getPageList().size());
        } catch (IOException e) {
            throw new RuntimeException(e);
        }
    }
注：对于这块代码的功能而言已经使用reader.getNumberOfPages();解决了。但是这个不兼容的情况还是存在。网上也找了资料，说是从外面一层xml文件中可以读取每一页的目录，仅供参考

**Comment by Trisia** [comment]
2.3.2 fix
