### ISSUE TITLE
对于"画"出来的字有没有办法提取

### ISSUE THREAD

**Issue by wupj1993** [ofdrw/ofdrw#296]
对于Doc_0/Pages/Page_0/Content.xml，其中这里面的都是svg画出来的汉字，如图
![QQ_1724057422894](https://github.com/user-attachments/assets/975aabba-a772-4be1-8a88-5c09d2226012)

使用page.getText()无法获取到文字，对于这种文档有没有好方法来提取文字

**Comment by Trisia** [comment]
实用阅读ocr

**Comment by Trisia** [comment]
阅读器ocr
