### ISSUE TITLE
Line颜色设置无效

### ISSUE THREAD

**Issue by zkbaymax** [ofdrw/ofdrw#300]
版本2.3.2 
示例代码 src/test/java/org/ofdrw/layout/element/canvas/LineTest.java
设置线条颜色无效果 
![image](https://github.com/user-attachments/assets/7d0fb1b5-adc6-4073-89d3-f66cd2550e72)
![image](https://github.com/user-attachments/assets/c22d691b-f3ab-4550-ae42-43f40fe382af)

**Comment by Trisia** [comment]
阅读器问题。
