### ISSUE TITLE
 java.lang.NoClassDefFoundError: org/ofdrw/converter/ConvertHelper

### ISSUE THREAD

**Issue by tenglongwentian** [ofdrw/ofdrw#308]
java.lang.NoClassDefFoundError: org/ofdrw/converter/ConvertHelper
springboot2.7.18
<dependency>
    <groupId>org.ofdrw</groupId>
    <artifactId>ofdrw-converter</artifactId>
    <version>2.3.3</version>
</dependency>

**Comment by Trisia** [comment]
导入full
