### ISSUE TITLE
冲突

### ISSUE THREAD

**Issue by tenglongwentian** [ofdrw/ofdrw#309]
<dependency>
            <groupId>org.bouncycastle</groupId>
            <artifactId>bcprov-jdk18on</artifactId>
            <version>${bcpkix.version}</version>
        </dependency>
        <dependency>
            <groupId>org.bouncycastle</groupId>
            <artifactId>bcpkix-jdk18on</artifactId>
            <version>${bcpkix.version}</version>
        </dependency>
与
<artifactId>bcprov-jdk15on</artifactId>
                    <groupId>org.bouncycastle</groupId>

<groupId>org.bouncycastle</groupId>
                    <artifactId>bcpkix-jdk15on</artifactId>

**Comment by Trisia** [comment]
依赖问题，请自行解决
