### ISSUE TITLE
ofdrw组件引入了AGPL协议组件itextpdf，协议不友好

### ISSUE THREAD

**Issue by XXXHHHDynasty** [ofdrw/ofdrw#320]
使用2.2.10版本ofdrw组件将ofd转png时，该功能有调用itextpdf组件接口，itextpdf组件为AGPL协议，协议不友好，同时也证明ofdrw组件的Apache 2.0协议不合规

**Comment by Trisia** [comment]
1. OFDRW项目所有代码均开源，无任何盈利内容，支持自由分发，满足Apache、AGPL要求。
2. OFDRW转换模块提供两种实现包括 PDFBox（Apache 2.0） 和 iText（AGPL），您可以删除相关实现代码以满足不同开源协议要求。
3. 开协议仅对软件进行宽松的约束，软件使用和知识产权保护以国家相关法律法规为准。

**Comment by XXXHHHDynasty** [comment]
有些工具类（如字体类、pdf转换类）里强依赖itext组件的接口，您看下能否完全剥离掉itext组件，使用pdfbox或其他组件的相似功能来替换，谢谢！

**Comment by XXXHHHDynasty** [comment]
@Trisia
