### ISSUE TITLE
文字抽取显示乱码问题

### ISSUE THREAD

**Issue by gweichang** [ofdrw/ofdrw#51]
使用ContentExtractorTest获取ofd文档内容，第一页标题文字显示正常，后续页面的中文全部乱码，例如：
<img width="728" alt="截屏2020-10-18 14 47 37" src="https://user-images.githubusercontent.com/49266004/96360573-f2977480-1150-11eb-83af-cf6fed8312bf.png">

以上，求解决方法。感谢！

**Comment by minghu-zhang** [comment]
完整OFD文件和测试代码能否上传一下

**Comment by minghu-zhang** [comment]
> 使用ContentExtractorTest获取ofd文档内容，第一页标题文字显示正常，后续页面的中文全部乱码，例如：
> <img alt="截屏2020-10-18 14 47 37" width="728" src="https://user-images.githubusercontent.com/49266004/96360573-f2977480-1150-11eb-83af-cf6fed8312bf.png">
> 
> 以上，求解决方法。感谢！

请确认下是否项目的字符编码问题！并将完整OFD文件和测试代码上传到git

**Comment by gweichang** [comment]
> git

项目编码为UTF-8。在文件读取过程中，没发现可以设置字符编码的地方。测试代码如下：
`void traverse() throws IOException {
        src = Paths.get("/Users/gao/Desktop/xxxx.ofd");
        try (OFDReader reader = new OFDReader(src)) {
            ContentExtractor extractor = new ContentExtractor(reader);
            extractor.traverse((pageNum, contents) -> {
                System.out.println("pageNum:"+pageNum);
                System.out.println("size:"+contents.size());
                contents.forEach(str -> {
                    System.out.println(str);
                });
                System.out.println("-------------------------------------------------------");
            });
        }`
ps：文件为保密资料，不方便提供。一级标题可以正常输出，内容部分乱码，是否可能和字体有关？

**Comment by minghu-zhang** [comment]
> > git
> 
> 项目编码为UTF-8。在文件读取过程中，没发现可以设置字符编码的地方。测试代码如下：
> `void traverse() throws IOException { src = Paths.get("/Users/gao/Desktop/xxxx.ofd"); try (OFDReader reader = new OFDReader(src)) { ContentExtractor extractor = new ContentExtractor(reader); extractor.traverse((pageNum, contents) -> { System.out.println("pageNum:"+pageNum); System.out.println("size:"+contents.size()); contents.forEach(str -> { System.out.println(str); }); System.out.println("-------------------------------------------------------"); }); }`
> ps：文件为保密资料，不方便提供。一级标题可以正常输出，内容部分乱码，是否可能和字体有关？

你的测试代码我这边试了确实没有乱码，你要不把内容脱敏之后上传一份，很可能和你的IDE有关系

**Comment by gweichang** [comment]
抱歉，文件来自客户，我不知道怎么去编辑OFD文件。
<img width="993" alt="image" src="https://user-images.githubusercontent.com/49266004/96429809-f3550700-1233-11eb-9c18-73a98b3da6db.png">
我检查了IDE的编码，全部是utf-8。
目前使用数科工具打开是正确的。使用这个项目生成新的OFD文件，然后解析也是正确的。
诡异的是部分乱码而不是全部乱码：
<img width="736" alt="image" src="https://user-images.githubusercontent.com/49266004/96430158-68284100-1234-11eb-8e27-60713e420c59.png">

**Comment by minghu-zhang** [comment]
> 抱歉，文件来自客户，我不知道怎么去编辑OFD文件。
> <img alt="image" width="993" src="https://user-images.githubusercontent.com/49266004/96429809-f3550700-1233-11eb-9c18-73a98b3da6db.png">
> 我检查了IDE的编码，全部是utf-8。
> 目前使用数科工具打开是正确的。使用这个项目生成新的OFD文件，然后解析也是正确的。
> 诡异的是部分乱码而不是全部乱码：
> <img alt="image" width="736" src="https://user-images.githubusercontent.com/49266004/96430158-68284100-1234-11eb-8e27-60713e420c59.png">

用zip把文件解压，然后找到 Doc_0\Pages\Page_0 类似这种路径，把Page_0 下面的Content.xml 内容脱敏上传一下吧，我这边修改了编码也没复现这个问题，抱歉

**Comment by minghu-zhang** [comment]
> > 抱歉，文件来自客户，我不知道怎么去编辑OFD文件。
> > <img alt="image" width="993" src="https://user-images.githubusercontent.com/49266004/96429809-f3550700-1233-11eb-9c18-73a98b3da6db.png">
> > 我检查了IDE的编码，全部是utf-8。
> > 目前使用数科工具打开是正确的。使用这个项目生成新的OFD文件，然后解析也是正确的。
> > 诡异的是部分乱码而不是全部乱码：
> > <img alt="image" width="736" src="https://user-images.githubusercontent.com/49266004/96430158-68284100-1234-11eb-8e27-60713e420c59.png">
> 
> 用zip把文件解压，然后找到 Doc_0\Pages\Page_0 类似这种路径，把Page_0 下面的Content.xml 内容脱敏上传一下吧，我这边修改了编码也没复现这个问题，抱歉

或者把

> 抱歉，文件来自客户，我不知道怎么去编辑OFD文件。
> <img alt="image" width="993" src="https://user-images.githubusercontent.com/49266004/96429809-f3550700-1233-11eb-9c18-73a98b3da6db.png">
> 我检查了IDE的编码，全部是utf-8。
> 目前使用数科工具打开是正确的。使用这个项目生成新的OFD文件，然后解析也是正确的。
> 诡异的是部分乱码而不是全部乱码：
> <img alt="image" width="736" src="https://user-images.githubusercontent.com/49266004/96430158-68284100-1234-11eb-8e27-60713e420c59.png">

或者把pageNum为2 的Content.xml 脱敏拷贝给我也可以

**Comment by gweichang** [comment]
[page0-2.zip](https://github.com/Trisia/ofdrw/files/5405880/page0-2.zip)
不知道什么原因，page2的内容解压后就乱码了，详情见附件……
辛苦了！

**Comment by minghu-zhang** [comment]
> [page0-2.zip](https://github.com/Trisia/ofdrw/files/5405880/page0-2.zip)
> 不知道什么原因，page2的内容解压后就乱码了，详情见附件……
> 辛苦了！

![image](https://user-images.githubusercontent.com/28996118/96536791-68bde780-12c7-11eb-82a8-9d584a9fd230.png)
你好，直接拷贝到ide里，显示是一些小图标，可能是输入的时候就有问题了，数科的能打开，但是他也展示不出来

**Comment by gweichang** [comment]
在不解压的情况下，直接使用数科阅读器打开是可以正确显示的。
我怀疑是解压过程出现了问题，所以分别在mac os和win10环境解压了这个文件，都是同样的乱码效果。

另外，使用工具speedpdf进行ofd转word的过程也可以正确识别。

**Comment by minghu-zhang** [comment]
> 在不解压的情况下，直接使用数科阅读器打开是可以正确显示的。
> 我怀疑是解压过程出现了问题，所以分别在mac os和win10环境解压了这个文件，都是同样的乱码效果。
> 
> 另外，使用工具speedpdf进行ofd转word的过程也可以正确识别。

我在看下

**Comment by minghu-zhang** [comment]
> 在不解压的情况下，直接使用数科阅读器打开是可以正确显示的。
> 我怀疑是解压过程出现了问题，所以分别在mac os和win10环境解压了这个文件，都是同样的乱码效果。
> 
> 另外，使用工具speedpdf进行ofd转word的过程也可以正确识别。

方便添加我Q么，协助复现一下，zip我解压缩目前没复现出乱码的情况

**Comment by minghu-zhang** [comment]
> 在不解压的情况下，直接使用数科阅读器打开是可以正确显示的。
> 我怀疑是解压过程出现了问题，所以分别在mac os和win10环境解压了这个文件，都是同样的乱码效果。
> 
> 另外，使用工具speedpdf进行ofd转word的过程也可以正确识别。

欢迎加入 577682453 在这里沟通吧，目前还没有复现

**Comment by gweichang** [comment]
> > 在不解压的情况下，直接使用数科阅读器打开是可以正确显示的。
> > 我怀疑是解压过程出现了问题，所以分别在mac os和win10环境解压了这个文件，都是同样的乱码效果。
> > 另外，使用工具speedpdf进行ofd转word的过程也可以正确识别。
> 
> 欢迎加入 577682453 Q群 在这里沟通吧，目前还没有复现

已申请，麻烦通过下，谢谢
我的QQ ： 513361564

**Comment by Trisia** [comment]
你的文档可能是使用转换工具从PDF转换的吧，里面使用到了而外的字体文件，这些字体文件都是都是通过精简的，精简过后的字体文件只保留了使到的文字。然后在使用的时候使用CGTransform进行映射。

**Comment by gweichang** [comment]
> 你的文档可能是使用转换工具从PDF转换的吧，里面使用到了而外的字体文件，这些字体文件都是都是通过精简的，精简过后的字体文件只保留了使到的文字。然后在使用的时候使用CGTransform进行映射。

文档是客户提供的，所以不太清楚它经历了什么……
